# Generated by Django 6.0.3 on 2026-03-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_forms', to='groups.group')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('group', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GroupPerformanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_form', to='finance.monthlyform')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'Section A – Advance Paid Today'), ('B', 'Section B – Cash Given Out Today'), ('C', 'Section C – Savings'), ('D', 'Section D – Loans'), ('E', 'Section E – Income'), ('F', 'Section F – Expenses'), ('G', 'Section G – Banking')], max_length=1)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('performance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.groupperformanceform')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('savings_share_bf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_balance_bf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shares_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fines_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_share_cf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_balance_cf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_valid', models.BooleanField(default=True)),
                ('loan_valid', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('monthly_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_records', to='finance.monthlyform')),
            ],
            options={
                'ordering': ['order', 'member__name'],
                'unique_together': {('monthly_form', 'member')},
            },
        ),
    ]
