# Generated by Django 6.0.3 on 2026-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceentry',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performanceentry',
            name='secondary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
