# Generated by Django 6.0.3 on 2026-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_performanceentry_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceentry',
            name='tertiary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
