# Generated by Django 6.0.3 on 2026-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_performanceentry_tertiary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceentry',
            name='section',
            field=models.CharField(choices=[('A', 'Section A – Advance Paid Today'), ('B', 'Section B – Cash Given Out Today'), ('C', 'Section C – Savings'), ('D', 'Section D – Loans'), ('G', 'Section G – Banking')], max_length=1),
        ),
    ]
