# Generated by Django 6.0.3 on 2026-03-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_performanceentry_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceentry',
            name='section',
            field=models.CharField(choices=[('A', 'Section A – Advance Paid Today'), ('B', 'Section B – Cash Given Out Today'), ('C', 'Section C – INCOME'), ('D', 'Section D – EXPENSES'), ('G', 'Section G – Banking')], max_length=1),
        ),
    ]
