# Generated by Django 5.1.5 on 2026-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_performanceentry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperformanceform',
            name='next_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupperformanceform',
            name='next_meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupperformanceform',
            name='next_meeting_venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceentry',
            name='section',
            field=models.CharField(choices=[('A', 'Section A – Advance Paid Today'), ('B', 'Section B – Cash Given Out Today'), ('C', 'Section C – INCOME'), ('D', 'Section D – EXPENSES'), ('E', 'Section E – Financial Reconciliation')], max_length=1),
        ),
    ]
