# Generated by Django 5.1.5 on 2026-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_expense_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='withdrawals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
