# Generated by Django 4.2.29 on 2026-04-11 18:30

from django.db import migrations, models
import django.utils.timezone
import uuid


def populate_finance_client_uuids(apps, schema_editor):
    Expense = apps.get_model('finance', 'Expense')
    MonthlyForm = apps.get_model('finance', 'MonthlyForm')

    for row in Expense.objects.filter(client_uuid__isnull=True).iterator():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=['client_uuid'])

    for row in MonthlyForm.objects.filter(client_uuid__isnull=True).iterator():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=['client_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_memberrecord_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='client_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='client_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='monthlyform',
            name='client_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlyform',
            name='client_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_finance_client_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlyform',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
