# Generated by Django 5.1.5 on 2026-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_groupperformanceform_and_performanceentry_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='loan_bf_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='savings_bf_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
