# Generated by Codex

import datetime
import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_group_client_updated_at_group_client_uuid'),
        ('finance', '0013_memberrecord_loan_bf_overridden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=80, unique=True)),
                ('receipt_date', models.DateField(default=datetime.date.today)),
                ('officer_name', models.CharField(max_length=200)),
                ('receipt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_deposited', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('missing_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('excess_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_receipts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='groups.group')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', 'group__name'],
                'unique_together': {('receipt_date', 'group')},
            },
        ),
        migrations.CreateModel(
            name='CashReceiptExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.cashreceipt')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
    ]
