# Generated by Django 5.1.5 on 2026-03-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ict', 'ICT'), ('officer', 'Data Entry Officer'), ('management', 'Management'), ('admin', 'Administrator')], default='officer', max_length=20),
        ),
    ]
