# Generated by Django 5.1.5 on 2026-03-17 14:48

from django.db import migrations


def populate_phone_numbers(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if not user.phone_number:
            user.phone_number = user.username
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(populate_phone_numbers),
    ]
