# Generated by Django 5.1.5 on 2026-03-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('january', models.CharField(blank=True, max_length=50, null=True)),
                ('february', models.CharField(blank=True, max_length=50, null=True)),
                ('march', models.CharField(blank=True, max_length=50, null=True)),
                ('april', models.CharField(blank=True, max_length=50, null=True)),
                ('may', models.CharField(blank=True, max_length=50, null=True)),
                ('june', models.CharField(blank=True, max_length=50, null=True)),
                ('july', models.CharField(blank=True, max_length=50, null=True)),
                ('august', models.CharField(blank=True, max_length=50, null=True)),
                ('september', models.CharField(blank=True, max_length=50, null=True)),
                ('october', models.CharField(blank=True, max_length=50, null=True)),
                ('november', models.CharField(blank=True, max_length=50, null=True)),
                ('december', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='groups.group')),
            ],
        ),
    ]
