# Generated by Django 5.1.5 on 2026-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banking_type',
            field=models.CharField(choices=[('office', 'Office Account'), ('group', 'Group Account')], default='office', max_length=20),
        ),
    ]
