# Generated by Django 4.2.29 on 2026-04-11 18:30

from django.db import migrations, models
import django.utils.timezone
import uuid


def populate_group_client_uuids(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')

    for row in Group.objects.filter(client_uuid__isnull=True).iterator():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=['client_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_banking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='client_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='client_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_group_client_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='group',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
