# Generated by Django 6.0.3 on 2026-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_diaryentry'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_number', 'name']},
        ),
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.PositiveIntegerField(blank=True, help_text='Permanent member number within this group', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('group', 'member_number')},
        ),
    ]
