# Generated by Django 4.2.29 on 2026-04-11 18:30

from django.db import migrations, models
import django.utils.timezone
import uuid


def populate_member_client_uuids(apps, schema_editor):
    Member = apps.get_model('members', 'Member')

    for row in Member.objects.filter(client_uuid__isnull=True).iterator():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=['client_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_member_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='client_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='client_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(populate_member_client_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='member',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
